#!/bin/bash

export PREFIX="poetry run"
export SOURCE_FILES="sqlsl"

set -x

${PREFIX} flake8 $SOURCE_FILES --exclude=__init__.py
${PREFIX} black --check --diff $SOURCE_FILES
${PREFIX} mypy $SOURCE_FILES
